style:
  ReturnCount:
    max: 3
  ThrowsCount:
    max: 3
  NestedClassesVisibility:
    active: false
  WildcardImport:
    excludeImports:
      - 'kotlinx.coroutines.*'
      - 'org.springframework.boot.autoconfigure.*'
      - 'org.springframework.context.annotation.*'

complexity:
  ComplexMethod:
    threshold: 15
  LongMethod:
    threshold: 60
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15

naming:
  VariableNaming:
    variablePattern: '[a-z][A-Za-z0-9]*'
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'

potential-bugs:
  UnsafeCast:
    active: true
  HasPlatformType:
    active: true

comments:
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false

coroutines:
  active: true
  InjectDispatcher:
    active: true
  RedundantSuspendModifier:
    active: true